### ISSUE TITLE
`sff.conf` not copied during install

### ISSUE THREAD

**Issue by paulkorir** [emdb-empiar/sfftk#16]
Here is the exception raised:

```
$ sff config get --all
Traceback (most recent call last):
  File "/Users/pkorir/miniconda2/envs/test-sfftk/bin/sff", line 8, in <module>
    sys.exit(main())
  File "/Users/pkorir/miniconda2/envs/test-sfftk/lib/python3.7/site-packages/sfftk/sff.py", line 561, in main
    args, configs = parse_args(sys.argv[1:])
  File "/Users/pkorir/miniconda2/envs/test-sfftk/lib/python3.7/site-packages/sfftk/core/parser.py", line 1058, in parse_args
    configs = load_configs(config_file_path)
  File "/Users/pkorir/miniconda2/envs/test-sfftk/lib/python3.7/site-packages/sfftk/core/configs.py", line 205, in load_configs
    configs.read()
  File "/Users/pkorir/miniconda2/envs/test-sfftk/lib/python3.7/site-packages/sfftk/core/configs.py", line 51, in read
    with open(self.config_fn, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pkorir/miniconda2/envs/test-sfftk/lib/python3.7/site-packages/sfftk/sff.conf'
```

The solution is to ensure the file `sff.conf` is copied during installation as shipped configs.

The same applies to the test data: none of the test data is copied.

Solution: see https://packaging.python.org/guides/distributing-packages-using-setuptools/#package-data for packaging data

**Comment by paulkorir** [comment]
Fixed in 74b13566e3a1c46ff747eaff9c8d232f2704924d
